using GraphQL.Types;

using abstractplay.Games;

namespace abstractplay.GraphQL
{
    public class GamesDataPreviewType : ObjectGraphType<Game> 
    {
        public GamesDataPreviewType()
        {
            Field<StringGraphType>(
                "renderRep",
                description: "The string representing the board state",
                resolve: _ => ((Game)_.Source).Render()
            );
            Field<StringGraphType>(
                "messages",
                description: "Any chat messages generated by the move",
                resolve: _ => ((Game)_.Source).ChatMsgs
            );
        }
    }
}